resources:
  - name: app_repo
    type: GitRepo
    configuration:
      gitProvider: Git                     # <-- replace with your integration
      path: app    # <-- replace with your repository name
      branches:
        include: dev

  - name: webapp_image
    type: Image
    configuration:
      registry: ido_artifactory                                # <-- replace with your artifactory integration
      sourceRepository: docker_local               # <-- required if registry is Artifactory
      imageName: docker-local/web-app/  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: app_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: ido_artifactory
      buildName: app_build
      buildNumber: 1    

  - name: app_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: ido_artifactory
      buildName: app_build
      buildNumber: 1
      

pipelines:
  - name: pipeline_app
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: webapp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: docker-local/web-app/  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: app_repo
          integrations:
            - name: ido_artifactory                            # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: webapp_group
          targetRepository: docker-local
          integrations:
            - name: ido_artifactory                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: webapp_image

      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: app_build_info

      - name: promote_app_build
        type: PromoteBuild
        configuration:
          targetRepository: docker-local
          integrations:
            - name: ido_artifactory
          inputResources:
            - name: app_build_info
          outputResources:
            - name: app_promoted_build_info